project_name: access-watcher

before:
  hooks:
    - make generate
builds:
  - main: ./cmd/access-watcher/main.go
    binary: bin/access-watcher
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
dockers:
  -
    image_templates:
    - "gcr.io/authorizer-tech/access-watcher:latest"
    - "gcr.io/authorizer-tech/access-watcher:{{ .Tag }}"
    - "gcr.io/authorizer-tech/access-watcher:v{{ .Major }}"
    - "gcr.io/authorizer-tech/access-watcher:v{{ .Major }}.{{ .Minor }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
